### ISSUE TITLE
Table Headings break site on mobile

### ISSUE THREAD

**Issue by sigul** [bradleytaunt/vanilla-css#3]
On my iPhone X, table headings are not contained in the cell and I think this provoke that unpleasant experience of horizontal scrolling / moving of the page 
![3AA0D6E5-7E58-4A5F-A6F8-B0887B1D1875](https://user-images.githubusercontent.com/7622916/76139602-da576700-6051-11ea-95f2-f212ce3db501.png)

**Comment by bradleytaunt** [comment]
Thanks for finding this bug! It should now be fixed via https://github.com/bradleytaunt/vanilla-css/commit/c48067006828f1df06e5dc9a1ab25d2ceea1f2d2 and live on the demo website.

Cheers!
