### ISSUE TITLE
I think the name "Vanilla CSS" is misleading

### ISSUE THREAD

**Issue by guettli** [bradleytaunt/vanilla-css#4]
If people talk about VanillaCSS or VanillaJS the usually mean "without libraries".

I think the name of the project is misleading.

**Comment by bradleytaunt** [comment]
Hey @guettli - I completely understand where you're coming from. The name `vanillacss` in this instance is referring to the fact that no classes, IDs or special characters are needed for this styling to work.

This isn't a "library" in my mind - the point is to simply snag this CSS and place it locally within your project. Hope that clarifies some things.

Cheers
