### ISSUE TITLE
Duplicates found for P margin

### ISSUE THREAD

**Issue by ghost** [bradleytaunt/vanilla-css#5]
Hi there,

I can see that paragraph has duplicate `margin` entries on lines https://github.com/bradleytaunt/vanilla-css/blob/6ecc574b9f594b4480f8de4604003fc821b0b787/vanilla.css#L50 and https://github.com/bradleytaunt/vanilla-css/blob/6ecc574b9f594b4480f8de4604003fc821b0b787/vanilla.css#L63 in vanilla.css

Is there any reason for duplicates?

**Comment by bradleytaunt** [comment]
Thank you for noticing! I've fixed this with: https://github.com/bradleytaunt/vanilla-css/commit/ab6120fba74eef4823221e4a75d767561bf3911a
